/*jshint laxcomma:true strict:false*/
/*globals module require*/

var fs          = require("fs")
  , jshint      = require("jshint").JSHINT
  , jsh_options = JSON.parse(fs.readFileSync(process.env.PWD + "/.jshintrc", "utf-8") || {});

function format_errors (item) {
  return "(" + item.line + ":" + item.character + ") - " + item.reason;
}

module.exports = function (munifex) {
  return function signifer_js (path, input, done) {
    if (/Generated by CoffeeScript/i.test(input) || jshint(input, jsh_options)) {
      done(input);
    } else {
      munifex("JSHint found these issue(s) with " + path + ".", true);
      munifex(jshint.errors.map(format_errors), true);
    }
  };
};
